### ISSUE TITLE
用demo一运行就报这些错，是什么问题

### ISSUE THREAD

**Issue by zannet** [jjeffcaii/socket.io#1]
客户端的请求链求是这样的:
https://xxx.xxx.xxx/socket.io/?EIO=3&transport=polling&t=1563507321405-0
报如下错：
2019/07/19 11:26:57 http: panic serving 127.0.0.1:13296: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc000076a00)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x6d2f60, 0x96e7a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
shouxia.net/live/vendor/github.com/jjeffcaii/socket%2eio.newHandshake(0x0, 0x0)
	/home/go/src/shouxia.net/live/vendor/github.com/jjeffcaii/socket.io/socket.go:161 +0x26
shouxia.net/live/vendor/github.com/jjeffcaii/socket%2eio.handleSocket(0xc000068f60, 0x780b60, 0xc000076b40, 0x0)
	/home/go/src/shouxia.net/live/vendor/github.com/jjeffcaii/socket.io/socket.go:171 +0x65
shouxia.net/live/vendor/github.com/jjeffcaii/socket%2eio.newServer.func1(0x780b60, 0xc000076b40)
	/home/go/src/shouxia.net/live/vendor/github.com/jjeffcaii/socket.io/server.go:79 +0x3e
shouxia.net/live/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).socketCreated(0xc000076960, 0xc000076b40)
	/home/go/src/shouxia.net/live/vendor/github.com/jjeffcaii/engine.io/engine.go:221 +0x67
shouxia.net/live/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).Router.func1(0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/home/go/src/shouxia.net/live/vendor/github.com/jjeffcaii/engine.io/engine.go:97 +0x35a
net/http.HandlerFunc.ServeHTTP(0xc000010d70, 0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
shouxia.net/live/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/home/go/src/shouxia.net/live/vendor/github.com/rs/cors/cors.go:219 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc00000c320, 0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x97aaa0, 0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00006b1e0, 0x77f4e0, 0xc0000f8000, 0xc0000f4000)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000076a00, 0x77f920, 0xc000050340)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

**Comment by jjeffcaii** [comment]
这个项目已经很久没有维护了。请问客户端版本是多少？能贴一些客户端的代码么？

**Comment by zannet** [comment]
> 这个项目已经很久没有维护了。请问客户端版本是多少？能贴一些客户端的代码么？
客户端的代码是这样，会一直报错
   var socket = io('https://live.xxxx.net', {
        transports: ['websocket']
    });
	// 连接后登录
	socket.on('connect', function(){
		socket.emit('login',{'uid':uid,'fkid':fkid,'xxtype':xxtype,'xxurl':xxurl});
	});

**Comment by zannet** [comment]
版本是2.0的 js客户端

**Comment by zannet** [comment]
去掉引入的cors包，还是一运行就报如下错
2019/07/19 13:56:55 http: panic serving 127.0.0.1:9822: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc00008caa0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x709a40, 0x9f27d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.newHandshake(...)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/socket.go:161
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.handleSocket(0xc000080de0, 0x7db200, 0xc00008cb40, 0xc00008cb40)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/socket.go:171 +0x62
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.newServer.func1(0x7db200, 0xc00008cb40)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/server.go:79 +0x3e
project.tv/project-chat/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).socketCreated(0xc00008ca00, 0xc00008cb40)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/engine.io/engine.go:221 +0x67
project.tv/project-chat/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).Router.func1(0x7d8700, 0xc00010e0e0, 0xc00010c000)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/engine.io/engine.go:97 +0x35d
net/http.HandlerFunc.ServeHTTP(0xc000012cb0, 0x7d8700, 0xc00010e0e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x9fef20, 0x7d8700, 0xc00010e0e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000088d00, 0x7d8700, 0xc00010e0e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00008caa0, 0x7d8e80, 0xc00005a580)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
2019/07/19 13:56:56 http: panic serving 127.0.0.1:9824: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc00014e000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x709a40, 0x9f27d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.newHandshake(...)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/socket.go:161
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.handleSocket(0xc000080de0, 0x7db200, 0xc00014e0a0, 0xc00014e0a0)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/socket.go:171 +0x62
project.tv/project-chat/vendor/github.com/jjeffcaii/socket%2eio.newServer.func1(0x7db200, 0xc00014e0a0)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/socket.io/server.go:79 +0x3e
project.tv/project-chat/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).socketCreated(0xc00008ca00, 0xc00014e0a0)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/engine.io/engine.go:221 +0x67
project.tv/project-chat/vendor/github.com/jjeffcaii/engine%2eio.(*engineImpl).Router.func1(0x7d8700, 0xc000174000, 0xc000162000)
	/data/go/src/project.tv/project-chat/vendor/github.com/jjeffcaii/engine.io/engine.go:97 +0x35d
net/http.HandlerFunc.ServeHTTP(0xc000012cb0, 0x7d8700, 0xc000174000, 0xc000162000)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x9fef20, 0x7d8700, 0xc000174000, 0xc000162000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000088d00, 0x7d8700, 0xc000174000, 0xc000162000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00014e000, 0x7d8e80, 0xc00015a040)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by jjeffcaii** [comment]
2.0的js客户端没有测试过。你能先试下用1.x的看看正常么？因为这个库还是一年多前写的，那时候版本比较低。

**Comment by zannet** [comment]
好的，大佬有时间能做下2.0的兼容不，Golang上能用的Socket.IO包好少，之前找的github.com/mlsquires/socketio这个包有缺陷，消息经常丢失.

**Comment by jjeffcaii** [comment]
得等我抽时间看下2.0的官方实现，这个项目实在太久没维护了 😂
要是方便的话你可以加我下微信jeffsky1024，有问题随时可以问我。

**Comment by zannet** [comment]
> jeffsky1024

谢谢 已加申请

**Comment by jjeffcaii** [comment]
临时先work around，请使用v0.0.2版本。后面我再排查。
